services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d 
    networks:
      - mattilda_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code
    networks:
      - mattilda_network
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local

networks:
  mattilda_network:
    driver: bridge