"""Remove student_id from Invoice model

Revision ID: 39ec9b57daf2
Revises: e5285b16f52d
Create Date: 2025-07-25 05:30:05.078494

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39ec9b57daf2"
down_revision: Union[str, Sequence[str], None] = "e5285b16f52d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("invoices_student_id_fkey"), "invoices", type_="foreignkey")
    op.drop_column("invoices", "student_id")
    op.alter_column("students", "school_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_username_key"), "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(
        op.f("users_username_key"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column("students", "school_id", existing_type=sa.UUID(), nullable=False)
    op.add_column(
        "invoices",
        sa.Column("student_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("invoices_student_id_fkey"),
        "invoices",
        "students",
        ["student_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
